# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
<<<<<<< HEAD

=======
env:
  Variables:
    OwaspZapURLName:
      Description: OWASP Zap DAST Tool URL
      Type: String
      Default: http://44.202.166.177
    ApplicationURLForDASTScan:
      Description: Application URL to run the DAST/Pen testing 
      Type: String
      Default: https://ec2-44-202-166-177.compute-1.amazonaws.com.
    OwaspZapApiKey:
      Description: OWASP Zap ApiKey
      Type: String
      NoEcho: 
      Default: 7e0ba806hu1r1ojr699v
>>>>>>> eb02ef6363f66a1f7110c9e636d33cac92d53388
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code

      #Dynamic Application Security Scan (DAST scan) using OWASP ZAP
      - sudo apt-get update && sudo apt-get upgrade
      - sudo apt-get install openjdk-11-jdk
      - sudo apt-get install wget
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2_11_1_unix.sh
      - cd Downloads/
      - sudo ./ZAP_2_11_1_unix.sh
      -zap.sh -daemon -quickurl https://demo.testfire.net/index.jsp -quickout /tmp/myresults.xml -quickprogress

        post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    -myresults.xml 
